### ISSUE TITLE
Should ignore code/fenced block

### ISSUE THREAD

**Issue by blueyed** [btford/write-good#62]
With a `t.md` file like the following, no errors should be reported:

```diff
--- /tmp/zshyQ69o4	2016-12-25 23:29:12.822000142 +0100
+++ /tmp/zshMuqqOv	2016-12-25 23:29:12.842000400 +0100
@@ -4988,9 +4988,9 @@
 000137b0  12 c6 08 17 94 d1 ff 17  a1 9b 74 be e4 47 27 ce  |..........t..G'.|
 000137c0  00 00 00 25 74 45 58 74  64 61 74 65 3a 63 72 65  |...%tEXtdate:cre|
 000137d0  61 74 65 00 32 30 31 36  2d 31 32 2d 32 35 54 32  |ate.2016-12-25T2|
-000137e0  32 3a 31 30 3a 32 35 2b  30 30 3a 30 30 e7 9f f3  |2:10:25+00:00...|
-000137f0  d5 00 00 00 25 74 45 58  74 64 61 74 65 3a 6d 6f  |....%tEXtdate:mo|
+000137e0  31 3a 34 32 3a 32 36 2b  30 30 3a 30 30 1e 1f f9  |1:42:26+00:00...|
+000137f0  f9 00 00 00 25 74 45 58  74 64 61 74 65 3a 6d 6f  |....%tEXtdate:mo|
 00013800  64 69 66 79 00 32 30 31  36 2d 31 32 2d 32 35 54  |dify.2016-12-25T|
-00013810  32 32 3a 31 30 3a 32 35  2b 30 30 3a 30 30 96 c2  |22:10:25+00:00..|
-00013820  4b 69 00 00 00 00 49 45  4e 44 ae 42 60 82        |Ki....IEND.B`.|
+00013810  32 31 3a 34 32 3a 32 36  2b 30 30 3a 30 30 6f 42  |21:42:26+00:00oB|
+00013820  41 45 00 00 00 00 49 45  4e 44 ae 42 60 82        |AE....IEND.B`.|
 0001382e
```

However, messages like the following get reported:

```
 000137c0  00 00 00 25 74 45 58 74  64 61 74 65 3a 63 72 65  |...%tEXtdate:cre|
              ^^
"00" is repeated on line 6 at column 14
```

**Comment by btford** [comment]
I think that a feature like this is beyond the scope of the simple CLI interface that write-good provides.

You can always create a similar tool using the programmatic API that ignores code blocks like this.

See https://github.com/btford/write-good/blob/master/bin/write-good.js

**Comment by revelt** [comment]
@btford Well, I can see the algorithm, it's not difficult: 
Count the instances of three consecutive left ticks in the input. Then, if the number is uneven, stop and do nothing — there are unclosed code blocks. If the number is even, skip checking between each even ID number of a left ticks block and uneven ID number of a left ticks block. Done.

I came here checking do issue tickets exist for skipping code, because I'm running this checker on a README files which naturally have inline code (well-marked by the way), and my HTML is triggering English grammar check errors:

![screen shot 2017-04-28 at 06 40 31](https://cloud.githubusercontent.com/assets/8344688/25515603/9eebf6dc-2bdd-11e7-9eea-2c5e82b058e5.png)

I would not underestimate the audience for this library, it's primarily developers and developers will always put code snippets in their documents. I think this is a valid issue and it's pity that we closed it.

**Comment by RichardLitt** [comment]
Well, one thing that could fix both of these issues is to simply check if numbers are being repeated. That would solve both of these two issues, I think.

**Comment by Couto** [comment]
>  would not underestimate the audience for this library, it's primarily developers and developers will always put code snippets in their documents. I think this is a valid issue and it's pity that we closed it.

Indeed, I'm having problems with code inside code blocks. Having a way to set text blocks to be explicitly ignore would be great, or a flag to say "ignore code blocks"
